import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MissionEngineProvider } from "@/components/providers/MissionEngineProvider";
import { AuthProvider } from "@/components/providers/AuthProvider";
import { VoiceProvider } from "@/components/providers/VoiceProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col text-gray-900 bg-[#FAFAFA] selection:bg-indigo-100 selection:text-indigo-900 overflow-hidden font-sans">
        <AuthProvider>
          <VoiceProvider>
            <MissionEngineProvider>
              {children}
            </MissionEngineProvider>
          </VoiceProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
